services:
  database:
    image: "postgres:alpine"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: ${DB_PORT}
    expose:
      - "${DB_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
  redis:
    depends_on:
      - database
    hostname: redis
    image: "redis:alpine"
    expose:
      - 6379
    volumes:
      - cache:/data
    restart: always
  backend:
    env_file: .env
    depends_on:
      - database
      - redis
    build: .
    ports:
      - "${PORT_MAIN}:${PORT_MAIN}/tcp"

volumes:
  cache:
    driver: local
  postgres-data:
    driver: local
